addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.3.5")
addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.16")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.0-M5")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.5")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.11")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.2-1")
